### PR TITLE
DOM Parsing and Serialization is RC since 14 June 2014

### PR DESCRIPTION
**Pull request by vanesyan**

### CODE REVIEW

**Comment by dret** [comment]
thanks for spotting the wrong URI! fixed via https://github.com/dret/HTML5-overview/commit/f78050195c28b7d1c42d2bb0a57b4601ac81af21

**Comment by dret** [comment]
seems like the official date for CR status is 6/17, accoring to http://www.w3.org/TR/2014/CR-DOM-Parsing-20140617/. i'll update the page when the CR is released, thanks for the heads up! since the MD is generated from XML, i cannot merge your pull request, but it's definitely appreciated.

**Comment by vanesyan** [comment]
Sorry my bad, didn't notice that. Thanks.

**Comment by dret** [comment]
added https://github.com/dret/HTML5-overview/commit/34affe45163eeee760068ae6571bd537b958f8f7 to make it more clear how the page is maintained.

**Comment by dret** [comment]
i am wondering what happened to that 6/17 publication date of the CR, but i guess it'll pop up in the publication feed pretty soon...

**Comment by dret** [comment]
well, since it's still sitting there with the 6/17 time stamp, i am assuming this is going to pop up in the publication feed soon and https://github.com/dret/HTML5-overview/commit/e7eceeb904f0d40c99155f9cf088ef8856450a41 addresses your issue. thanks again!

**Pull request closed without merging**
